"""
Database Module – SQLite Persistence via SQLAlchemy

Provides persistent storage for:
  - Signals: every signal generated
  - Candidates: scored option candidates
  - Trades: entries, exits, P&L
  - Positions: active position state (replaces JSON file)
  - DailyStats: daily summary (trades, P&L, win rate)
  - Config snapshots: settings at each session start

Usage:
    from database import db, Signal, Trade, DailyStats
    db.init()  # creates tables if not exist
    db.save_signal(signal_data)
    trades = db.get_trades_for_date(date.today())
"""
import logging
from datetime import datetime, date
from typing import Optional, List, Dict, Any

from sqlalchemy import (
    create_engine, Column, Integer, Float, String, Boolean,
    DateTime, Date, Text, JSON, Index,
)
from sqlalchemy.orm import sessionmaker, declarative_base
from config import settings

logger = logging.getLogger(__name__)

Base = declarative_base()


# ── Models ──────────────────────────────────────────────────────────

class SignalRecord(Base):
    """Every signal generated by any strategy."""
    __tablename__ = "signals"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    trade_date = Column(Date, default=date.today, index=True)
    strategy = Column(String(50), default="ORB_BREAKOUT")
    instrument = Column(String(20), default="NIFTY")
    signal_type = Column(String(10))          # BUY / SELL / HOLD
    spot_price = Column(Float, default=0)
    entry_price = Column(Float, default=0)
    stop_loss = Column(Float, default=0)
    target = Column(Float, default=0)
    confidence = Column(Float, default=0)
    conditions = Column(Text, default="")     # JSON string of conditions
    reasoning = Column(Text, default="")
    gap_type = Column(String(20), default="NONE")
    vix = Column(Float, default=0)
    executed = Column(Boolean, default=False)  # was a trade placed?

    __table_args__ = (
        Index("ix_signal_date_strategy", "trade_date", "strategy"),
    )


class CandidateRecord(Base):
    """Scored option candidates per signal."""
    __tablename__ = "candidates"

    id = Column(Integer, primary_key=True, autoincrement=True)
    signal_id = Column(Integer, index=True)   # FK to signals.id (logical)
    timestamp = Column(DateTime, default=datetime.utcnow)
    trade_date = Column(Date, default=date.today, index=True)
    tradingsymbol = Column(String(50))
    strike = Column(Float)
    option_type = Column(String(2))           # CE / PE
    expiry = Column(String(15))
    ltp = Column(Float, default=0)
    delta = Column(Float, default=0)
    iv = Column(Float, default=0)
    iv_percentile = Column(Float, default=50)
    score = Column(Float, default=0)
    volume = Column(Integer, default=0)
    oi = Column(Integer, default=0)
    oi_change_pct = Column(Float, default=0)
    bid = Column(Float, default=0)
    ask = Column(Float, default=0)
    gap_type = Column(String(20), default="NONE")
    is_expiry_day = Column(Boolean, default=False)


class TradeRecord(Base):
    """Executed trades — entries and exits."""
    __tablename__ = "trades"

    id = Column(Integer, primary_key=True, autoincrement=True)
    trade_id = Column(String(40), unique=True, index=True)
    signal_id = Column(Integer, nullable=True)
    timestamp = Column(DateTime, default=datetime.utcnow)
    trade_date = Column(Date, default=date.today, index=True)
    instrument = Column(String(20), default="NIFTY")
    tradingsymbol = Column(String(50))
    option_type = Column(String(2))
    strike = Column(Float, default=0)
    direction = Column(String(4))             # BUY / SELL
    entry_price = Column(Float, default=0)
    entry_time = Column(DateTime, nullable=True)
    exit_price = Column(Float, default=0)
    exit_time = Column(DateTime, nullable=True)
    quantity = Column(Integer, default=0)
    pnl = Column(Float, default=0)
    pnl_pct = Column(Float, default=0)
    status = Column(String(10), default="OPEN")  # OPEN / CLOSED
    exit_reason = Column(String(30), default="")
    score = Column(Float, default=0)
    sl_initial = Column(Float, default=0)
    sl_final = Column(Float, default=0)
    target1 = Column(Float, default=0)
    target2 = Column(Float, default=0)
    target3 = Column(Float, default=0)
    trailing_phase = Column(String(20), default="INITIAL")
    strategy = Column(String(50), default="ORB_BREAKOUT")
    slippage = Column(Float, default=0)       # estimated slippage in ₹

    __table_args__ = (
        Index("ix_trade_date_status", "trade_date", "status"),
    )


class DailyStats(Base):
    """Daily summary stats."""
    __tablename__ = "daily_stats"

    id = Column(Integer, primary_key=True, autoincrement=True)
    trade_date = Column(Date, unique=True, index=True)
    total_trades = Column(Integer, default=0)
    winning_trades = Column(Integer, default=0)
    losing_trades = Column(Integer, default=0)
    gross_pnl = Column(Float, default=0)
    net_pnl = Column(Float, default=0)        # after slippage
    max_drawdown = Column(Float, default=0)
    win_rate = Column(Float, default=0)        # 0-100%
    avg_winner = Column(Float, default=0)
    avg_loser = Column(Float, default=0)
    profit_factor = Column(Float, default=0)   # gross winners / gross losers
    capital_used = Column(Float, default=0)
    signals_generated = Column(Integer, default=0)
    signals_executed = Column(Integer, default=0)
    vix_avg = Column(Float, default=0)
    gap_type = Column(String(20), default="NONE")
    strategies_used = Column(Text, default="")  # comma-separated


class PositionSnapshot(Base):
    """Active position state (replaces JSON save/load)."""
    __tablename__ = "position_snapshots"

    id = Column(Integer, primary_key=True, autoincrement=True)
    trade_id = Column(String(40), unique=True, index=True)
    snapshot_time = Column(DateTime, default=datetime.utcnow)
    symbol = Column(String(50))
    option_type = Column(String(2))
    entry_price = Column(Float, default=0)
    quantity = Column(Integer, default=0)
    remaining_qty = Column(Integer, default=0)
    trailing_sl = Column(Float, default=0)
    trailing_phase = Column(String(20), default="INITIAL")
    highest_price = Column(Float, default=0)
    score = Column(Float, default=0)
    status = Column(String(10), default="OPEN")
    smart_levels_json = Column(Text, default="{}")  # JSON serialization


# ── Database Manager ────────────────────────────────────────────────

class DatabaseManager:
    """SQLite database manager using SQLAlchemy."""

    def __init__(self, db_url: Optional[str] = None):
        self.db_url = db_url or settings.database_url.replace("+aiosqlite", "")
        self.engine = None
        self.Session = None
        self._initialized = False

    def init(self):
        """Create tables if they don't exist."""
        if self._initialized:
            return
        try:
            self.engine = create_engine(self.db_url, echo=False)
            Base.metadata.create_all(self.engine)
            self.Session = sessionmaker(bind=self.engine)
            self._initialized = True
            logger.info(f"Database initialized: {self.db_url}")
        except Exception as e:
            logger.error(f"Database init failed: {e}")
            self._initialized = False

    def _get_session(self):
        if not self._initialized:
            self.init()
        return self.Session()

    # ── Signal operations ──

    def save_signal(self, **kwargs) -> Optional[int]:
        """Save a signal record. Returns signal ID."""
        try:
            session = self._get_session()
            record = SignalRecord(**kwargs)
            session.add(record)
            session.commit()
            sig_id = record.id
            session.close()
            return sig_id
        except Exception as e:
            logger.error(f"DB save_signal error: {e}")
            return None

    def get_signals_for_date(self, trade_date: date) -> List[Dict]:
        """Get all signals for a date."""
        try:
            session = self._get_session()
            records = session.query(SignalRecord).filter(
                SignalRecord.trade_date == trade_date
            ).order_by(SignalRecord.timestamp.desc()).all()
            result = [
                {
                    "id": r.id, "timestamp": r.timestamp.isoformat(),
                    "strategy": r.strategy, "signal_type": r.signal_type,
                    "spot_price": r.spot_price, "entry_price": r.entry_price,
                    "confidence": r.confidence, "executed": r.executed,
                    "gap_type": r.gap_type, "vix": r.vix,
                }
                for r in records
            ]
            session.close()
            return result
        except Exception as e:
            logger.error(f"DB get_signals error: {e}")
            return []

    # ── Candidate operations ──

    def save_candidates(self, signal_id: int, candidates: List[Dict]):
        """Save scored candidates for a signal."""
        try:
            session = self._get_session()
            for c in candidates:
                record = CandidateRecord(signal_id=signal_id, **c)
                session.add(record)
            session.commit()
            session.close()
        except Exception as e:
            logger.error(f"DB save_candidates error: {e}")

    # ── Trade operations ──

    def save_trade(self, **kwargs) -> bool:
        """Save or update a trade record."""
        try:
            session = self._get_session()
            trade_id = kwargs.get("trade_id")
            existing = session.query(TradeRecord).filter(
                TradeRecord.trade_id == trade_id
            ).first()
            if existing:
                for k, v in kwargs.items():
                    if hasattr(existing, k):
                        setattr(existing, k, v)
            else:
                record = TradeRecord(**kwargs)
                session.add(record)
            session.commit()
            session.close()
            return True
        except Exception as e:
            logger.error(f"DB save_trade error: {e}")
            return False

    def close_trade(
        self, trade_id: str, exit_price: float, exit_reason: str,
        pnl: float = 0, trailing_phase: str = "",
    ) -> bool:
        """Mark trade as closed with exit details."""
        try:
            session = self._get_session()
            trade = session.query(TradeRecord).filter(
                TradeRecord.trade_id == trade_id
            ).first()
            if trade:
                trade.exit_price = exit_price
                trade.exit_time = datetime.utcnow()
                trade.exit_reason = exit_reason
                trade.pnl = pnl
                trade.pnl_pct = (pnl / (trade.entry_price * trade.quantity) * 100) if trade.entry_price > 0 and trade.quantity > 0 else 0
                trade.status = "CLOSED"
                trade.trailing_phase = trailing_phase
                session.commit()
            session.close()
            return True
        except Exception as e:
            logger.error(f"DB close_trade error: {e}")
            return False

    def get_trades_for_date(self, trade_date: date) -> List[Dict]:
        """Get all trades for a date."""
        try:
            session = self._get_session()
            records = session.query(TradeRecord).filter(
                TradeRecord.trade_date == trade_date
            ).order_by(TradeRecord.entry_time.desc()).all()
            result = [
                {
                    "trade_id": r.trade_id, "tradingsymbol": r.tradingsymbol,
                    "option_type": r.option_type, "direction": r.direction,
                    "entry_price": r.entry_price, "exit_price": r.exit_price,
                    "quantity": r.quantity, "pnl": r.pnl,
                    "status": r.status, "exit_reason": r.exit_reason,
                    "strategy": r.strategy, "score": r.score,
                    "entry_time": r.entry_time.isoformat() if r.entry_time else "",
                    "exit_time": r.exit_time.isoformat() if r.exit_time else "",
                }
                for r in records
            ]
            session.close()
            return result
        except Exception as e:
            logger.error(f"DB get_trades error: {e}")
            return []

    def get_open_trades(self) -> List[Dict]:
        """Get all currently open trades."""
        try:
            session = self._get_session()
            records = session.query(TradeRecord).filter(
                TradeRecord.status == "OPEN"
            ).all()
            result = [
                {
                    "trade_id": r.trade_id, "tradingsymbol": r.tradingsymbol,
                    "entry_price": r.entry_price, "quantity": r.quantity,
                    "sl_initial": r.sl_initial, "score": r.score,
                }
                for r in records
            ]
            session.close()
            return result
        except Exception as e:
            logger.error(f"DB get_open_trades error: {e}")
            return []

    # ── Daily stats operations ──

    def save_daily_stats(self, trade_date: date, **kwargs) -> bool:
        """Save or update daily stats."""
        try:
            session = self._get_session()
            existing = session.query(DailyStats).filter(
                DailyStats.trade_date == trade_date
            ).first()
            if existing:
                for k, v in kwargs.items():
                    if hasattr(existing, k):
                        setattr(existing, k, v)
            else:
                record = DailyStats(trade_date=trade_date, **kwargs)
                session.add(record)
            session.commit()
            session.close()
            return True
        except Exception as e:
            logger.error(f"DB save_daily_stats error: {e}")
            return False

    def compute_and_save_daily_stats(self, trade_date: date) -> Dict:
        """Compute daily stats from trades and save."""
        trades = self.get_trades_for_date(trade_date)
        closed = [t for t in trades if t["status"] == "CLOSED"]

        total = len(closed)
        winners = [t for t in closed if t["pnl"] > 0]
        losers = [t for t in closed if t["pnl"] <= 0]

        gross_pnl = sum(t["pnl"] for t in closed)
        gross_winners = sum(t["pnl"] for t in winners) if winners else 0
        gross_losers = abs(sum(t["pnl"] for t in losers)) if losers else 0

        stats = {
            "total_trades": total,
            "winning_trades": len(winners),
            "losing_trades": len(losers),
            "gross_pnl": round(gross_pnl, 2),
            "net_pnl": round(gross_pnl, 2),  # TODO: subtract slippage
            "win_rate": round(len(winners) / total * 100, 1) if total > 0 else 0,
            "avg_winner": round(gross_winners / len(winners), 2) if winners else 0,
            "avg_loser": round(gross_losers / len(losers), 2) if losers else 0,
            "profit_factor": round(gross_winners / gross_losers, 2) if gross_losers > 0 else 0,
            "signals_generated": len(trades),
            "signals_executed": total,
        }

        self.save_daily_stats(trade_date, **stats)
        return stats

    def get_daily_stats_range(
        self, from_date: date, to_date: date
    ) -> List[Dict]:
        """Get daily stats for a date range (for equity curve)."""
        try:
            session = self._get_session()
            records = session.query(DailyStats).filter(
                DailyStats.trade_date >= from_date,
                DailyStats.trade_date <= to_date,
            ).order_by(DailyStats.trade_date).all()
            result = [
                {
                    "date": r.trade_date.isoformat(),
                    "total_trades": r.total_trades,
                    "net_pnl": r.net_pnl,
                    "win_rate": r.win_rate,
                    "profit_factor": r.profit_factor,
                    "max_drawdown": r.max_drawdown,
                }
                for r in records
            ]
            session.close()
            return result
        except Exception as e:
            logger.error(f"DB get_daily_stats_range error: {e}")
            return []

    # ── Position snapshot operations ──

    def save_position_snapshot(self, **kwargs) -> bool:
        """Save or update a position snapshot."""
        try:
            session = self._get_session()
            trade_id = kwargs.get("trade_id")
            existing = session.query(PositionSnapshot).filter(
                PositionSnapshot.trade_id == trade_id
            ).first()
            if existing:
                for k, v in kwargs.items():
                    if hasattr(existing, k):
                        setattr(existing, k, v)
                existing.snapshot_time = datetime.utcnow()
            else:
                record = PositionSnapshot(**kwargs)
                session.add(record)
            session.commit()
            session.close()
            return True
        except Exception as e:
            logger.error(f"DB save_position error: {e}")
            return False

    def get_active_position_snapshots(self) -> List[Dict]:
        """Get all active (non-closed) position snapshots."""
        try:
            session = self._get_session()
            records = session.query(PositionSnapshot).filter(
                PositionSnapshot.status != "CLOSED"
            ).all()
            result = [
                {
                    "trade_id": r.trade_id, "symbol": r.symbol,
                    "option_type": r.option_type, "entry_price": r.entry_price,
                    "quantity": r.quantity, "remaining_qty": r.remaining_qty,
                    "trailing_sl": r.trailing_sl, "trailing_phase": r.trailing_phase,
                    "highest_price": r.highest_price, "score": r.score,
                    "status": r.status,
                }
                for r in records
            ]
            session.close()
            return result
        except Exception as e:
            logger.error(f"DB get_positions error: {e}")
            return []

    def remove_position_snapshot(self, trade_id: str) -> bool:
        """Remove a closed position snapshot."""
        try:
            session = self._get_session()
            session.query(PositionSnapshot).filter(
                PositionSnapshot.trade_id == trade_id
            ).delete()
            session.commit()
            session.close()
            return True
        except Exception as e:
            logger.error(f"DB remove_position error: {e}")
            return False


# Global instance
db = DatabaseManager()
