"""
Trade Journal – End-of-Day (EOD) Report Generator

Tracks every signal (call) generated by the engine, whether it was
activated (actually traded), entry/exit prices, P&L, and duration.

Sends a comprehensive Telegram report after market close (3:30 PM IST).
Also exposes data for the dashboard API.
"""
import logging
from dataclasses import dataclass, field
from typing import Dict, List, Optional
from datetime import datetime, date, timedelta

logger = logging.getLogger(__name__)


# ============================================================
# Data classes
# ============================================================

@dataclass
class SignalRecord:
    """Every trade call / signal the engine generates."""
    signal_id: str                    # Unique ID
    timestamp: str                    # When the signal was generated
    signal_type: str                  # BUY / SELL
    spot_price: float                 # NIFTY spot at signal time
    entry_price: float                # Suggested entry
    stop_loss: float                  # Suggested SL
    target: float                     # Suggested target
    confidence: float                 # Signal confidence %
    conditions: List[str] = field(default_factory=list)
    reasoning: str = ""
    source: str = ""                  # e.g. "ORB_BREAKOUT", "SUPERTREND"


@dataclass
class CandidateRecord:
    """Each option candidate recommended by the scoring engine."""
    candidate_id: str
    signal_id: str                    # Links to the parent signal
    timestamp: str
    symbol: str                       # e.g. NIFTY2560524500CE
    display_name: str
    option_type: str                  # CE / PE
    strike: float
    expiry: str
    entry_price: float                # Option premium entry
    stop_loss: float                  # Option SL
    target1: float
    target2: float
    target3: float
    score: float
    delta: float
    iv: float
    risk_reward_pct: float
    # Activation tracking
    activated: bool = False           # Was this actually traded?
    trade_id: str = ""                # Links to risk_manager TradeRecord
    actual_entry_price: float = 0.0
    actual_entry_time: str = ""
    actual_exit_price: float = 0.0
    actual_exit_time: str = ""
    actual_pnl: float = 0.0
    quantity: int = 0
    exit_reason: str = ""
    status: str = "SIGNAL_ONLY"       # SIGNAL_ONLY / ACTIVE / CLOSED


# ============================================================
# Trade Journal
# ============================================================

class TradeJournal:
    """
    Central journal that records:
    1. Every signal generated
    2. Every candidate recommended
    3. Which candidates were actually traded (activated)
    4. Final P&L, entry/exit, duration for each

    Designed for EOD reporting.
    """

    def __init__(self):
        self.signals: List[SignalRecord] = []
        self.candidates: List[CandidateRecord] = []
        self._last_reset_date: Optional[date] = None

    # ------------------------------------------------------------------
    # Daily reset
    # ------------------------------------------------------------------
    def reset_daily(self):
        today = date.today()
        if self._last_reset_date == today:
            return
        self._last_reset_date = today
        self.signals.clear()
        self.candidates.clear()
        logger.info(f"Trade journal reset for {today}")

    # ------------------------------------------------------------------
    # Record a signal
    # ------------------------------------------------------------------
    def record_signal(
        self,
        signal_type: str,
        spot_price: float,
        entry_price: float,
        stop_loss: float,
        target: float,
        confidence: float,
        conditions: List[str] = None,
        reasoning: str = "",
        source: str = "",
    ) -> str:
        """Record a new signal. Returns signal_id."""
        now = datetime.now()
        signal_id = f"SIG-{now.strftime('%H%M%S')}-{len(self.signals)+1}"
        rec = SignalRecord(
            signal_id=signal_id,
            timestamp=now.isoformat(),
            signal_type=signal_type,
            spot_price=spot_price,
            entry_price=entry_price,
            stop_loss=stop_loss,
            target=target,
            confidence=confidence,
            conditions=conditions or [],
            reasoning=reasoning,
            source=source,
        )
        self.signals.append(rec)
        logger.info(f"Journal: signal recorded {signal_id} ({signal_type} @ {spot_price:.2f})")
        return signal_id

    # ------------------------------------------------------------------
    # Record candidates for a signal
    # ------------------------------------------------------------------
    def record_candidates(
        self, signal_id: str, scored_candidates: list
    ) -> List[str]:
        """
        Record top scored candidates for a signal.
        `scored_candidates` should be OptionCandidate objects from scoring_engine.
        Returns list of candidate_ids.
        """
        ids = []
        now = datetime.now()
        for i, c in enumerate(scored_candidates):
            cid = f"{signal_id}-C{i+1}"
            rec = CandidateRecord(
                candidate_id=cid,
                signal_id=signal_id,
                timestamp=now.isoformat(),
                symbol=getattr(c, "tradingsymbol", ""),
                display_name=getattr(c, "display_name", ""),
                option_type=getattr(c, "option_type", ""),
                strike=getattr(c, "strike", 0),
                expiry=getattr(c, "expiry", ""),
                entry_price=getattr(c, "entry_price", getattr(c, "ltp", 0)),
                stop_loss=getattr(c, "stoploss", 0),
                target1=getattr(c, "target1", 0),
                target2=getattr(c, "target2", 0),
                target3=getattr(c, "target3", 0),
                score=getattr(c, "score", 0),
                delta=getattr(c, "delta", 0),
                iv=getattr(c, "iv", 0),
                risk_reward_pct=getattr(c, "risk_reward_pct", 0),
            )
            self.candidates.append(rec)
            ids.append(cid)
        logger.info(f"Journal: {len(ids)} candidates recorded for {signal_id}")
        return ids

    # ------------------------------------------------------------------
    # Mark a candidate as activated (actually traded)
    # ------------------------------------------------------------------
    def activate_candidate(
        self,
        symbol: str,
        trade_id: str,
        entry_price: float,
        quantity: int,
    ):
        """Mark the most recent unactivated candidate for this symbol as traded."""
        for c in reversed(self.candidates):
            if c.symbol == symbol and not c.activated:
                c.activated = True
                c.trade_id = trade_id
                c.actual_entry_price = entry_price
                c.actual_entry_time = datetime.now().isoformat()
                c.quantity = quantity
                c.status = "ACTIVE"
                logger.info(f"Journal: candidate {c.candidate_id} activated as trade {trade_id}")
                return
        logger.warning(f"Journal: no unactivated candidate found for {symbol}")

    # ------------------------------------------------------------------
    # Close a candidate (trade exited)
    # ------------------------------------------------------------------
    def close_candidate(
        self,
        trade_id: str,
        exit_price: float,
        pnl: float,
        exit_reason: str,
    ):
        """Update the candidate record when a trade is closed."""
        for c in self.candidates:
            if c.trade_id == trade_id and c.activated:
                c.actual_exit_price = exit_price
                c.actual_exit_time = datetime.now().isoformat()
                c.actual_pnl = pnl
                c.exit_reason = exit_reason
                c.status = "CLOSED"
                logger.info(
                    f"Journal: candidate {c.candidate_id} closed. "
                    f"P&L=₹{pnl:+.2f} reason={exit_reason}"
                )
                return
        logger.warning(f"Journal: no activated candidate found for trade {trade_id}")

    # ------------------------------------------------------------------
    # Compute duration
    # ------------------------------------------------------------------
    @staticmethod
    def _compute_duration(entry_time: str, exit_time: str) -> str:
        """Compute human-readable duration between ISO timestamps."""
        if not entry_time or not exit_time:
            return "—"
        try:
            t_entry = datetime.fromisoformat(entry_time)
            t_exit = datetime.fromisoformat(exit_time)
            delta = t_exit - t_entry
            total_secs = int(delta.total_seconds())
            if total_secs < 0:
                return "—"
            hours = total_secs // 3600
            minutes = (total_secs % 3600) // 60
            secs = total_secs % 60
            if hours > 0:
                return f"{hours}h {minutes}m"
            elif minutes > 0:
                return f"{minutes}m {secs}s"
            else:
                return f"{secs}s"
        except Exception:
            return "—"

    @staticmethod
    def _compute_duration_minutes(entry_time: str, exit_time: str) -> float:
        """Compute duration in minutes."""
        if not entry_time or not exit_time:
            return 0.0
        try:
            t_entry = datetime.fromisoformat(entry_time)
            t_exit = datetime.fromisoformat(exit_time)
            return max(0, (t_exit - t_entry).total_seconds() / 60)
        except Exception:
            return 0.0

    # ------------------------------------------------------------------
    # Generate EOD Report Data
    # ------------------------------------------------------------------
    def generate_eod_report(self, risk_status: Dict = None) -> Dict:
        """
        Generate comprehensive EOD report data.
        Returns a dict with all trade journal details.
        """
        today_str = date.today().strftime("%d %b %Y")

        # --- Signal summary ---
        total_signals = len(self.signals)

        # --- Candidate breakdown ---
        total_candidates = len(self.candidates)
        activated = [c for c in self.candidates if c.activated]
        not_activated = [c for c in self.candidates if not c.activated]
        closed_trades = [c for c in activated if c.status == "CLOSED"]
        active_trades = [c for c in activated if c.status == "ACTIVE"]

        # --- P&L stats ---
        total_pnl = sum(c.actual_pnl for c in closed_trades)
        winners = [c for c in closed_trades if c.actual_pnl > 0]
        losers = [c for c in closed_trades if c.actual_pnl < 0]
        breakeven = [c for c in closed_trades if c.actual_pnl == 0]

        win_rate = (len(winners) / len(closed_trades) * 100) if closed_trades else 0
        avg_win = (sum(c.actual_pnl for c in winners) / len(winners)) if winners else 0
        avg_loss = (sum(c.actual_pnl for c in losers) / len(losers)) if losers else 0
        best_trade = max(closed_trades, key=lambda c: c.actual_pnl) if closed_trades else None
        worst_trade = min(closed_trades, key=lambda c: c.actual_pnl) if closed_trades else None

        # --- Duration stats ---
        durations = [
            self._compute_duration_minutes(c.actual_entry_time, c.actual_exit_time)
            for c in closed_trades
            if c.actual_entry_time and c.actual_exit_time
        ]
        avg_duration_min = (sum(durations) / len(durations)) if durations else 0
        max_duration_min = max(durations) if durations else 0
        min_duration_min = min(durations) if durations else 0

        # --- Build per-trade detail ---
        trade_details = []
        for c in self.candidates:
            detail = {
                "candidate_id": c.candidate_id,
                "signal_id": c.signal_id,
                "symbol": c.symbol,
                "display_name": c.display_name,
                "option_type": c.option_type,
                "strike": c.strike,
                "expiry": c.expiry,
                "signal_time": c.timestamp,
                "suggested_entry": c.entry_price,
                "suggested_sl": c.stop_loss,
                "suggested_t1": c.target1,
                "suggested_t2": c.target2,
                "suggested_t3": c.target3,
                "score": c.score,
                "delta": c.delta,
                "iv": c.iv,
                "risk_reward_pct": c.risk_reward_pct,
                "activated": c.activated,
                "status": c.status,
            }

            if c.activated:
                dur_str = self._compute_duration(c.actual_entry_time, c.actual_exit_time)
                dur_min = self._compute_duration_minutes(c.actual_entry_time, c.actual_exit_time)
                detail.update({
                    "trade_id": c.trade_id,
                    "actual_entry": c.actual_entry_price,
                    "entry_time": c.actual_entry_time,
                    "actual_exit": c.actual_exit_price,
                    "exit_time": c.actual_exit_time,
                    "quantity": c.quantity,
                    "pnl": round(c.actual_pnl, 2),
                    "exit_reason": c.exit_reason,
                    "duration": dur_str,
                    "duration_minutes": round(dur_min, 1),
                })

            trade_details.append(detail)

        # --- Build signal details ---
        signal_details = []
        for s in self.signals:
            sig_candidates = [c for c in self.candidates if c.signal_id == s.signal_id]
            sig_activated = [c for c in sig_candidates if c.activated]
            signal_details.append({
                "signal_id": s.signal_id,
                "timestamp": s.timestamp,
                "type": s.signal_type,
                "spot_price": s.spot_price,
                "entry": s.entry_price,
                "sl": s.stop_loss,
                "target": s.target,
                "confidence": s.confidence,
                "conditions": s.conditions,
                "source": s.source,
                "candidates_generated": len(sig_candidates),
                "candidates_activated": len(sig_activated),
            })

        # --- Format avg duration ---
        def _fmt_min(mins: float) -> str:
            if mins <= 0:
                return "—"
            h = int(mins) // 60
            m = int(mins) % 60
            return f"{h}h {m}m" if h > 0 else f"{m}m"

        report = {
            "date": today_str,
            "generated_at": datetime.now().isoformat(),

            # Summary
            "summary": {
                "total_signals": total_signals,
                "total_candidates": total_candidates,
                "activated_count": len(activated),
                "not_activated_count": len(not_activated),
                "closed_count": len(closed_trades),
                "still_active_count": len(active_trades),
                "total_pnl": round(total_pnl, 2),
                "winners": len(winners),
                "losers": len(losers),
                "breakeven": len(breakeven),
                "win_rate": round(win_rate, 1),
                "avg_win": round(avg_win, 2),
                "avg_loss": round(avg_loss, 2),
                "best_trade_pnl": round(best_trade.actual_pnl, 2) if best_trade else 0,
                "best_trade_symbol": best_trade.display_name if best_trade else "—",
                "worst_trade_pnl": round(worst_trade.actual_pnl, 2) if worst_trade else 0,
                "worst_trade_symbol": worst_trade.display_name if worst_trade else "—",
                "avg_duration": _fmt_min(avg_duration_min),
                "avg_duration_minutes": round(avg_duration_min, 1),
                "longest_trade": _fmt_min(max_duration_min),
                "shortest_trade": _fmt_min(min_duration_min),
            },

            # Risk info
            "risk": risk_status or {},

            # Detailed breakdowns
            "signals": signal_details,
            "trades": trade_details,
        }

        return report

    # ------------------------------------------------------------------
    # Generate Telegram-formatted EOD message
    # ------------------------------------------------------------------
    def generate_eod_telegram(self, risk_status: Dict = None) -> List[str]:
        """
        Generate Telegram-formatted EOD report messages.
        Returns a list of messages (split to stay within Telegram's 4096 char limit).
        """
        report = self.generate_eod_report(risk_status)
        s = report["summary"]
        messages = []

        # --- Message 1: Summary ---
        pnl_emoji = "💚" if s["total_pnl"] >= 0 else "❤️"
        msg1 = (
            f"📋 <b>END OF DAY REPORT</b>\n"
            f"━━━━━━━━━━━━━━━━━━━━\n"
            f"📅 {report['date']}\n\n"
            f"{pnl_emoji} <b>Net P&L: ₹{s['total_pnl']:+,.2f}</b>\n\n"
            f"📊 <b>Overview</b>\n"
            f"  Signals generated: {s['total_signals']}\n"
            f"  Candidates recommended: {s['total_candidates']}\n"
            f"  Trades activated: {s['activated_count']}\n"
            f"  Not activated: {s['not_activated_count']}\n"
            f"  Still open: {s['still_active_count']}\n\n"
            f"📈 <b>Performance</b>\n"
            f"  Winners: {s['winners']} | Losers: {s['losers']} | BE: {s['breakeven']}\n"
            f"  Win Rate: <b>{s['win_rate']:.0f}%</b>\n"
            f"  Avg Win: ₹{s['avg_win']:+,.2f}\n"
            f"  Avg Loss: ₹{s['avg_loss']:+,.2f}\n\n"
            f"🏆 Best: {s['best_trade_symbol']} (₹{s['best_trade_pnl']:+,.2f})\n"
            f"💀 Worst: {s['worst_trade_symbol']} (₹{s['worst_trade_pnl']:+,.2f})\n\n"
            f"⏱️ <b>Duration</b>\n"
            f"  Avg: {s['avg_duration']} | "
            f"Longest: {s['longest_trade']} | "
            f"Shortest: {s['shortest_trade']}\n"
        )
        messages.append(msg1)

        # --- Message 2: Activated trades (detailed) ---
        activated = [t for t in report["trades"] if t["activated"]]
        if activated:
            msg2 = "📝 <b>ACTIVATED TRADES</b>\n━━━━━━━━━━━━━━━━━━━━\n\n"
            for i, t in enumerate(activated, 1):
                pnl = t.get("pnl", 0)
                pnl_icon = "✅" if pnl > 0 else ("❌" if pnl < 0 else "➖")
                entry_t = t.get("entry_time", "")
                exit_t = t.get("exit_time", "")
                entry_short = entry_t[11:16] if len(entry_t) > 16 else "—"
                exit_short = exit_t[11:16] if len(exit_t) > 16 else "—"

                trade_line = (
                    f"{pnl_icon} <b>{i}. {t['display_name']}</b>\n"
                    f"  Entry: ₹{t['actual_entry']:.2f} → Exit: ₹{t.get('actual_exit', 0):.2f}\n"
                    f"  P&L: <b>₹{pnl:+,.2f}</b> | Qty: {t.get('quantity', 0)}\n"
                    f"  Time: {entry_short} → {exit_short} ({t.get('duration', '—')})\n"
                    f"  Reason: {t.get('exit_reason', 'OPEN')}\n"
                    f"  Score: {t['score']:.0f} | SL: ₹{t['suggested_sl']:.0f} | "
                    f"T1: ₹{t['suggested_t1']:.0f}\n\n"
                )

                # Check if adding this trade would exceed Telegram limit
                if len(msg2) + len(trade_line) > 3900:
                    messages.append(msg2)
                    msg2 = f"📝 <b>ACTIVATED TRADES (cont.)</b>\n\n"

                msg2 += trade_line

            messages.append(msg2)

        # --- Message 3: Non-activated calls ---
        not_activated = [t for t in report["trades"] if not t["activated"]]
        if not_activated:
            msg3 = "📢 <b>CALLS NOT ACTIVATED</b>\n━━━━━━━━━━━━━━━━━━━━\n\n"
            for i, t in enumerate(not_activated, 1):
                sig_time = t.get("signal_time", "")
                sig_short = sig_time[11:16] if len(sig_time) > 16 else "—"

                call_line = (
                    f"📌 {i}. {t['display_name']} ({t['option_type']})\n"
                    f"  Entry: ₹{t['suggested_entry']:.0f} | "
                    f"SL: ₹{t['suggested_sl']:.0f} | "
                    f"T1: ₹{t['suggested_t1']:.0f}\n"
                    f"  Score: {t['score']:.0f} | Time: {sig_short}\n\n"
                )

                if len(msg3) + len(call_line) > 3900:
                    messages.append(msg3)
                    msg3 = f"📢 <b>CALLS NOT ACTIVATED (cont.)</b>\n\n"

                msg3 += call_line

            messages.append(msg3)

        # --- Message 4: Signal summary ---
        if report["signals"]:
            msg4 = "📡 <b>SIGNALS GENERATED</b>\n━━━━━━━━━━━━━━━━━━━━\n\n"
            for sig in report["signals"]:
                sig_time = sig["timestamp"][11:16] if len(sig["timestamp"]) > 16 else "—"
                msg4 += (
                    f"{'🟢' if sig['type'] == 'BUY' else '🔴'} "
                    f"<b>{sig['type']}</b> @ {sig_time}\n"
                    f"  Spot: {sig['spot_price']:.2f} | "
                    f"Conf: {sig['confidence']:.0f}%\n"
                    f"  Candidates: {sig['candidates_generated']} → "
                    f"Activated: {sig['candidates_activated']}\n\n"
                )

                if len(msg4) > 3900:
                    messages.append(msg4)
                    msg4 = f"📡 <b>SIGNALS (cont.)</b>\n\n"

            messages.append(msg4)

        # If no activity at all
        if not messages:
            messages.append(
                f"📋 <b>END OF DAY REPORT</b>\n"
                f"━━━━━━━━━━━━━━━━━━━━\n"
                f"📅 {report['date']}\n\n"
                f"No signals or trades today.\n"
                f"⏰ {datetime.now().strftime('%H:%M')}"
            )

        return messages

    # ------------------------------------------------------------------
    # API data
    # ------------------------------------------------------------------
    def get_journal_data(self) -> Dict:
        """Return raw journal data for API endpoints."""
        return {
            "date": date.today().isoformat(),
            "signals_count": len(self.signals),
            "candidates_count": len(self.candidates),
            "activated_count": len([c for c in self.candidates if c.activated]),
            "signals": [
                {
                    "signal_id": s.signal_id,
                    "timestamp": s.timestamp,
                    "type": s.signal_type,
                    "spot": s.spot_price,
                    "confidence": s.confidence,
                    "source": s.source,
                }
                for s in self.signals
            ],
            "candidates": [
                {
                    "candidate_id": c.candidate_id,
                    "signal_id": c.signal_id,
                    "symbol": c.symbol,
                    "display_name": c.display_name,
                    "option_type": c.option_type,
                    "entry_price": c.entry_price,
                    "stop_loss": c.stop_loss,
                    "target1": c.target1,
                    "score": c.score,
                    "activated": c.activated,
                    "status": c.status,
                    "trade_id": c.trade_id,
                    "actual_entry": c.actual_entry_price,
                    "actual_exit": c.actual_exit_price,
                    "pnl": round(c.actual_pnl, 2),
                    "exit_reason": c.exit_reason,
                    "duration": self._compute_duration(
                        c.actual_entry_time, c.actual_exit_time
                    ) if c.activated else "—",
                }
                for c in self.candidates
            ],
        }


# Singleton
trade_journal = TradeJournal()
